### ISSUE TITLE
Customization on the Website

### ISSUE THREAD

**Issue by danielmarv** [AgricHub/AgricHub-Emarket#26]
Please you requested to provide a full customized website for the Hub Website

**Comment by wajaht-ali** [comment]
Hello @danielmarv, I am interested in solving the issue. Would you like to assign it to me?

**Comment by danielmarv** [comment]
> Hello @danielmarv, I am interested in solving the issue. Would you like to assign it to me?

but it could be better when you read properly the docs for the pproject
